services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: every-challenge
      POSTGRES_PASSWORD: every-challenge
      POSTGRES_DB: every-challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://every-challenge:every-challenge@db:5432/every-challenge?schema=public
      PORT: 3000
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
